multilingual support

diff --git a/ssq b/ssq
--- a/ssq
+++ b/ssq
@@ -3,6 +3,11 @@
 MAX_EXTRA_ITEMS=10
 BULLET=$(echo -ne '\u26AB')
 
+lang=$2
+if [ -z "$lang" ]; then
+	lang=en
+fi
+
 function prune() {
 	sed 's/<br \/>/\n/g' | sed 's/<span class="w">\([^<]*\)<\/span>/(\1)/g; s/<\/\?[^>]*>//g; s/^\s\+//g; s/ \+,  \?/, /g; s/&rarr;/->/g' | tr -s ' '
 }
@@ -15,23 +20,27 @@ function grepTag() {
 	grep -Po "$1.*?</$(echo \"$1\" | grep -Po '(?<=<)[a-zA-Z0-9_]+')>"
 }
 
-uri="https://slovnik.seznam.cz/en/?q=$1&shortView=0"
-shortened=0
-
-result=$(curl $uri 2>/dev/null | tr -s [:space:] | grep -v -e '^[[:space:]]*$' | tr '\t\r\n' '   ')
+result=$(curl -G --data-urlencode "shortView=0" --data-urlencode "q=$1" "https://slovnik.seznam.cz/$lang/" 2>/dev/null | tr -s [:space:] | grep -v -e '^[[:space:]]*$' | tr '\t\r\n' '   ')
 found="$(echo "$result" | grepTag '<h3.*?notFirst.*?>' | prune)"
 
 if [ -z "$found" ]; then
-	echo "ssq: $1: not found" >&2
-	mistype=$(echo "$result" | grepTag '<ul class="mistype">' | prune)
-	if [ ! -z "$mistype" ]; then
-		echo "ssq: hint: did you mean any of the following?"
-		echo "$mistype" | sed 's/<\/li>/<br \/>/g' | listify
+	more=$(echo "$result" | grepTag '<ul class="moreResults">')
+	if [ -z "$more" ]; then
+		echo "ssq: $1: not found" >&2
+		mistype=$(echo "$result" | grepTag '<ul class="mistype">')
+		if [ ! -z "$mistype" ]; then
+			echo "ssq: hint: did you mean any of the following?"
+			echo "$mistype" | sed 's/<\/li>/<br \/>/g' | prune | listify
+		fi
+		exit 1
+	else
+		echo "$(echo "$result" | grepTag '<h3.*?>' | prune) (non-perfect match):"
+		echo "$more" | sed 's/<\/li>/<br \/>/g' | prune | listify
+		exit 0
 	fi
-	exit 1
 fi
 
-echo $found: | tr [:lower:] [:upper:]
+echo $found:
 echo "$result" | grepTag '<div id="fastMeanings">' | prune | listify
 
 advanced=$(echo "$result" | grepTag "<dl>" | sed 's/<\/dt>/<br \/>____/g' | prune)
@@ -43,7 +52,6 @@ if [ ! -z "$advanced" ]; then
 	if [ $(echo "$advanced" | wc -l) -gt $MAX_EXTRA_ITEMS ]; then
 		echo
 		echo -e "\t (there's more)"
-		shortened=1
 	fi
 fi
 
@@ -56,7 +64,6 @@ if [ ! -z "$syno" ]; then
 	if [ $(echo "$syno" | wc -l) -gt $MAX_EXTRA_ITEMS ]; then
 		echo
 		echo -e "\t (there's more)"
-		shortened=1
 	fi
 fi
 
@@ -68,11 +75,5 @@ if [ ! -z "$fulltext" ]; then
 	if [ $(echo "$fulltext" | wc -l) -gt $MAX_EXTRA_ITEMS ]; then
 		echo
 		echo -e "\t (there's more)"
-		shortened=1
 	fi
-fi
-
-if [ $shortened -ne 0 ]; then
-	echo
-	echo "See $uri for more."
 fi
